import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import StyledJsxRegistry from './registry'

import Header from './components/Header'
import AuthSession from './AuthSession'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.png',
  },
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledJsxRegistry>
          <AuthSession>
            <Header />
            {children}
          </AuthSession>
        </StyledJsxRegistry>
      </body>
    </html>
  )
}
