import './globals.css'
import StyledJsxRegistry from './registry'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Header from './components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.png',
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledJsxRegistry>
          <Header />
          {children}
        </StyledJsxRegistry>
      </body>
    </html>
  )
}
